### ISSUE TITLE
Need Null check in sample02. FollowerAI.cs

### ISSUE THREAD

**Issue by nicecapj** [ejonghyuck/UniBt#2]
In Sample02.
For case of lost target, need checking for null.

[Callstack]
NullReferenceException: Object reference not set to an instance of an object
UniBt.Example.FollowerAI.<RapidMoveToTarget>m__0 (UniRx.Unit _) (at Assets/UniBt/Examples/Sample02/Scripts/FollowerAI.cs:79)
UniRx.Observer+AnonymousObserver`1[UniRx.Unit].OnNext (UniRx.Unit value) (at Assets/UniBt/UniRx/Scripts/Observer.cs:55)

**Comment by ejonghyuck** [comment]
Thank you for your interest in UniBt.
I had checked the problem of this issue, so that soon I'll fix it.

If you have questions or opinions to UniBt, please join UniBt's gitter chat.
:us:(Eng) : https://gitter.im/ejonghyuck/UniBt
:kr:(Kor) : https://gitter.im/ejonghyuck/UniBt/korean

Or tweet to [@HansMakart](https://twitter.com/HansMakart).
